# Generated by Django 5.1.7 on 2025-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrcodes/'),
        ),
    ]
