# Generated by Django 5.1.7 on 2025-05-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feewaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.feecategory'),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='myapp.student'),
        ),
    ]
