# Generated by Django 5.1.7 on 2025-05-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_feewaiver_category_alter_feewaiver_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='form',
        ),
    ]
