# Generated by Django 5.1.7 on 2025-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_student_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_mode', models.CharField(choices=[('term', 'Term-based Collection'), ('annual', 'Annual Collection')], default='term', max_length=10)),
                ('due_date', models.IntegerField(choices=[(1, '1st'), (5, '5th'), (10, '10th'), (15, '15th')], default=10)),
                ('grace_period', models.IntegerField(default=5, help_text='Number of days after due date before late penalty applies')),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of late payment penalty', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Setting',
                'verbose_name_plural': 'Fee Settings',
            },
        ),
    ]
