# Generated by Django 5.1.7 on 2025-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('view_payment_details', 'Can view payment details'), ('view_payment_sensitive_data', 'Can view payment sensitive data')]},
        ),
        migrations.AddField(
            model_name='payment',
            name='_encrypted_bank_account',
            field=models.CharField(blank=True, db_column='bank_account', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='_encrypted_card_number',
            field=models.CharField(blank=True, db_column='card_number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='_encrypted_transaction_id',
            field=models.CharField(blank=True, db_column='transaction_id', max_length=255, null=True),
        ),
    ]
