# Generated by Django 5.1.7 on 2025-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fraud_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='estimated_days_to_completion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='predicted_completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='predicted_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='sentiment_subjectivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=200),
        ),
    ]
