# Generated by Django 5.1.6 on 2025-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, help_text="Student's class", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('form', 'Form'), ('standard', 'Standard'), ('others', 'Others')], help_text="Student's level (year/form/standard/others)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level_custom',
            field=models.CharField(blank=True, help_text="Custom level value when 'others' is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, help_text="Student's program", max_length=100, null=True),
        ),
    ]
