# Generated by Django 5.1.6 on 2025-07-31 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_student_class_name_student_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(choices=[('general', 'General'), ('individual', 'Individual Student')], default='general', help_text='General categories apply to all students, Individual categories are for specific students', max_length=20),
        ),
        migrations.CreateModel(
            name='IndividualStudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the fee (e.g., Overtime Fee, Demerit Penalty)', max_length=100)),
                ('description', models.TextField(help_text='Description of why this fee was applied')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'individual'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.feecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_individual_fees', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_fees', to='myapp.student')),
            ],
            options={
                'verbose_name': 'Individual Student Fee',
                'verbose_name_plural': 'Individual Student Fees',
                'ordering': ['-created_at'],
            },
        ),
    ]
