# Generated by Django 5.1.6 on 2025-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_feecategory_category_type_individualstudentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='e_poster',
            field=models.ImageField(blank=True, help_text='Upload an e-poster for the donation event', null=True, upload_to='donation_events/posters/'),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='formal_letter',
            field=models.FileField(blank=True, help_text='Upload a formal letter document (PDF, DOC, etc.)', null=True, upload_to='donation_events/letters/'),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture for the donation event', null=True, upload_to='donation_events/pictures/'),
        ),
    ]
