# Generated by Django 5.1.6 on 2025-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_donationevent_e_poster_donationevent_formal_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='auto_generate_payments',
            field=models.BooleanField(default=False, help_text='Automatically generate monthly payment records for students'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='monthly_duration',
            field=models.IntegerField(blank=True, choices=[(10, '10 months'), (11, '11 months'), (12, '12 months')], help_text='Number of months for monthly payment plan (only for monthly frequency)', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to be paid over the monthly duration', max_digits=10, null=True),
        ),
    ]
