# Generated by Django 5.1.6 on 2025-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_add_monthly_payment_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
