# Generated by Django 5.1.6 on 2025-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['category__name', 'form']},
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='form',
            field=models.CharField(help_text='Form/grade level (e.g., Form 1, Form 2, Form 3)', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('school_fees_admin', 'School Fees Admin'), ('donation_admin', 'Donation Admin'), ('waqaf_admin', 'Waqaf Admin')], default='student', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('category', 'form')},
        ),
    ]
