# Generated by Django 5.1.6 on 2025-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_userprofile_role_parentcart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
