# Generated by Django 5.1.6 on 2025-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent'), ('donation_admin', 'Donation Admin'), ('waqaf_admin', 'Waqaf Admin')], default='student', max_length=30),
        ),
    ]
