# Generated by Django 5.1.6 on 2025-09-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_create_parent_cart_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PibgDonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_message', models.TextField(default="Support our school's PIBG Muafakat fund to help improve facilities and student programs.", help_text='Message shown to users about the donation')),
                ('preset_amounts', models.JSONField(default=list, help_text='Preset donation amounts in RM')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether donation selection is mandatory during checkout')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether the donation feature is enabled')),
                ('minimum_custom_amount', models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum amount for custom donations', max_digits=10)),
                ('maximum_custom_amount', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum amount for custom donations', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PIBG Donation Settings',
                'verbose_name_plural': 'PIBG Donation Settings',
            },
        ),
        migrations.CreateModel(
            name='PibgDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pibg_donations', to='myapp.parent')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pibg_donations', to='myapp.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pibg_donations', to='myapp.student')),
            ],
            options={
                'verbose_name': 'PIBG Muafakat Donation',
                'verbose_name_plural': 'PIBG Muafakat Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
