# Generated by Django 5.1.6 on 2025-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_add_pibg_donation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedDonationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this amount is available for selection')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which amounts are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predefined Donation Amount',
                'verbose_name_plural': 'Predefined Donation Amounts',
                'ordering': ['display_order', 'amount'],
            },
        ),
    ]
