# Generated by Django 5.1.6 on 2025-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_predefineddonationamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibgdonationsettings',
            name='banner_text',
            field=models.CharField(default='PIBG Muafakat Fund Donation', help_text='Banner text displayed above the donation section', max_length=200),
        ),
    ]
