# Generated by Django 5.1.6 on 2025-09-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_pibgdonationsettings_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('student', 'Student'), ('parent', 'Parent'), ('donation_admin', 'Donation Module Admin'), ('waqaf_admin', 'Waqaf Module Admin'), ('school_fees_admin', 'School Fees Module Admin'), ('school_fees_level_admin', 'School Fees Level Admin')], default='student', max_length=30),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('donation', 'Donation Module'), ('waqaf', 'Waqaf Module'), ('school_fees', 'School Fees Module'), ('pibg_donation', 'PIBG Donation')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='myapp.userprofile')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'unique_together': {('user_profile', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SchoolFeesLevelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('form5', 'Form 5'), ('year1', 'Year 1'), ('year2', 'Year 2'), ('year3', 'Year 3'), ('year4', 'Year 4'), ('year5', 'Year 5'), ('standard1', 'Standard 1'), ('standard2', 'Standard 2'), ('standard3', 'Standard 3'), ('standard4', 'Standard 4'), ('standard5', 'Standard 5'), ('standard6', 'Standard 6'), ('all', 'All Levels')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_manage_fees', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assignments', to='myapp.userprofile')),
            ],
            options={
                'verbose_name': 'School Fees Level Admin',
                'verbose_name_plural': 'School Fees Level Admins',
                'unique_together': {('user_profile', 'level')},
            },
        ),
    ]
