# Generated by Django 5.1.6 on 2025-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_userprofile_role_modulepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
