# Generated by Django 5.1.6 on 2025-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_student_year_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number", max_length=15, null=True),
        ),
    ]
