# Generated by Django 5.2.3 on 2025-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
