# Generated by Django 5.1.7 on 2025-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationevent',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
