# Generated by Django 5.1.7 on 2025-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation2', '0002_alter_donationevent_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationevent',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrcodes/'),
        ),
    ]
