# Generated by Django 5.1.7 on 2025-06-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation2', '0003_alter_donationevent_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationEvent',
        ),
    ]
