# Generated by Django 5.1.7 on 2025-06-09 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation2', '0004_delete_donationevent'),
        ('myapp', '0014_donation_fraud_probability_donation_is_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorEngagementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('thank_you', 'Thank You Message'), ('impact_report', 'Impact Report'), ('reengagement', 'Re-engagement Suggestion'), ('anniversary', 'Anniversary Message')], max_length=20)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_messages', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_messages', to='myapp.donationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
