# Generated by Django 5.2.3 on 2025-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation2', '0006_donationcart_donationcartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Online Payment', 'Online Payment')], max_length=20),
        ),
    ]
