# Generated by Django 5.1.6 on 2025-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('waqaf_admin', 'Waqaf Admin'), ('student', 'Student'), ('regular', 'Regular User')], default='regular', max_length=20),
        ),
    ]
