# Generated by Django 5.1.6 on 2025-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('waqaf_admin', 'Waqaf Admin'), ('donation_admin', 'Donation Admin'), ('form1_admin', 'Form 1 Admin'), ('form3_admin', 'Form 3 Admin'), ('student', 'Student'), ('regular', 'Regular User')], default='regular', max_length=20),
        ),
    ]
