# Generated by Django 5.1.7 on 2025-04-28 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_contributed', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waqaf.waqafasset')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waqaf.contributor')),
            ],
        ),
    ]
