# Generated by Django 5.1.7 on 2025-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0002_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='waqafasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waqafasset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='waqafasset',
            name='value',
        ),
        migrations.AddField(
            model_name='contributor',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waqafasset',
            name='description',
            field=models.TextField(),
        ),
    ]
