# Generated by Django 5.1.7 on 2025-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0003_remove_contributor_address_remove_contributor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqafasset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
