# Generated by Django 5.1.7 on 2025-05-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0004_waqafasset_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='number_of_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waqafasset',
            name='slot_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='waqafasset',
            name='slots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waqafasset',
            name='total_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waqaf.waqafasset'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
