# Generated by Django 5.1.7 on 2025-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0005_contribution_number_of_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='dedicated_for',
            field=models.CharField(blank=True, help_text='E.g. For late mother, father, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_type',
            field=models.CharField(choices=[('ONE_OFF', 'One-off'), ('RECURRING', 'Recurring (Bank Auto-Deduction)')], default='ONE_OFF', max_length=20),
        ),
    ]
