# Generated by Django 5.1.7 on 2025-05-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0006_contribution_dedicated_for_contribution_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
