# Generated by Django 5.1.7 on 2025-05-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0007_contribution_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='certificate',
        ),
    ]
