# Generated by Django 5.1.6 on 2025-08-08 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0008_remove_contribution_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='auto_generate_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_schedule',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payments_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='total_payments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment'), ('AUTO_DEDUCTION', 'Auto Deduction')], max_length=20, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='waqaf.contribution')),
            ],
            options={
                'ordering': ['due_date', 'payment_number'],
                'unique_together': {('contribution', 'payment_number')},
            },
        ),
    ]
