# Generated by Django 5.1.6 on 2025-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0009_contribution_auto_generate_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqafasset',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount needed for this asset', max_digits=10),
        ),
    ]
