# Generated by Django 5.2.3 on 2025-08-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0012_waqafasset_archive_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waqafasset',
            options={'ordering': ['name'], 'verbose_name': 'Waqaf Asset', 'verbose_name_plural': 'Waqaf Assets'},
        ),
    ]
