# Generated by Django 5.2.3 on 2025-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waqaf', '0013_alter_waqafasset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment'), ('AUTO_DEDUCTION', 'Auto Deduction')], max_length=20, null=True),
        ),
    ]
